## SeeAct Platform configuration (Demo mode)
## Aligned with README scope: agent, sandbox/patcher, calibration, runner, AVI, reporting.

[basic]
is_demo = true # Demo mode: interactive prompts for task and URL. False = read tasks from JSON (auto/online modes).
save_file_dir = "../online_results" # Output directory for logs/artifacts; keep git-ignored and out of version control.
default_task ="Find pdf of paper \"GPT-4V(ision) is a Generalist Web Agent, if Grounded\" from arXiv" # Example default task used if user presses Enter.
default_website = "https://www.google.com/" # Example default start URL used if user presses Enter.

[experiment]
task_file_path = "../data/online_tasks/sample_tasks.json" # Auto/online mode task list (ignored when is_demo=true).
overwrite = false # Overwrite existing outputs in save_file_dir; false skips completed tasks.
top_k = 50  # Candidate pruning for element selection if a ranker is enabled.
fixed_choice_batch_size = 17 # Max options per multiple-choice prompt.
# Keep small to avoid huge screenshots that may crash Playwright.
dynamic_choice_batch_size=1600 # Overrides fixed batch by page height if >0.
max_continuous_no_op = 2 # Stop after this many consecutive ineffective operations.
max_op = 20 # Global cap on operations per task.
highlight = false # Draw boxes for variant diffs in screenshots (useful for reporting).
monitor = true # Human-in-the-loop confirmation each step; keep true during development for safety.
dev_mode=false # Extra logging/diagnostics.
# storage_state="" # Optional cookies/session file path (avoid automating logins in development).
# ranker_path = "../model/deberta-v3-base" # Optional element ranker; comment out to consider all candidates.
# Example reference: https://huggingface.co/osunlp/MindAct_CandidateGeneration_deberta-v3-base

[openai]
# Provider configuration for the SeeAct agent (set keys via env; see README Quick Start).
rate_limit = -1 # Per-process throttle; set >0 to avoid provider rate-limits.
model = "gpt-4-vision-preview" # LMM used by the agent; swap as needed.
temperature = 0 # Lower = more deterministic, matching “one rationale → one tool call per step”.

[oss_model]
# Placeholder for configuring open-source providers/models if desired.

[playwright]
save_video = false # Save session videos; heavy, use for debugging.
tracing = false # Save Playwright traces; heavy, not for routine runs.
locale="en-US" # Browser locale.
geolocation.longitude=39.99542778404405 # Browser geolocation (lon).
geolocation.latitude=-83.0068669912263 # Browser geolocation (lat).
viewport.width = 1280 # Browser viewport width.
viewport.height = 720 # Browser viewport height.
trace.screenshots = true # Timeline screenshots for reporting/debugging.
trace.snapshots = true # DOM snapshots enable sandbox/variant patcher and network stubbing analysis.
trace.sources = true # Include source files in traces for deeper inspection.
