## SeeAct config for running with an OpenAI fine‑tuned model
## Replace the model ID below with your actual fine‑tuned model.

[basic]
is_demo = false
save_file_dir = "../online_results"    # change to an absolute path (e.g., $HOME/Downloads/seeact_artifacts) if desired
default_task = "Open the homepage and find a product"
default_website = "https://example.com/"

[experiment]
task_file_path = "../data/online_tasks/sample_tasks.json"  # tasks relative to project base (folder above src)
overwrite = false
top_k = 50
fixed_choice_batch_size = 17
dynamic_choice_batch_size = 1600
max_continuous_no_op = 2
max_op = 20
highlight = false
monitor = true
dev_mode = false

[openai]
# Set your OPENAI_API_KEY in the environment. Then point to your fine‑tuned model ID below.
rate_limit = -1
model = "ft:gpt-4o-mini:org:proj:YOUR_FINE_TUNE_ID"   # <-- replace with your model ID
temperature = 0

[oss_model]

[playwright]
save_video = false
tracing = false
locale = "en-US"
geolocation.longitude = 0
geolocation.latitude = 0
viewport.width = 1280
viewport.height = 720
trace.screenshots = true
trace.snapshots = true
trace.sources = true

[runtime]
provider = "local"   # or "browserbase" with [runtime].cdp_url and headers
# cdp_url = "${BROWSERBASE_CDP_URL}"
# headers = { Authorization = "Bearer ${BROWSERBASE_API_KEY}" }

[runner]
concurrency = 6
max_retries = 2
backoff_base_sec = 1.5
backoff_max_sec = 15.0
task_timeout_sec = 180
metrics_dir = "../runs"

# For text‑only fine‑tunes, add this under a new [agent] section to disable screenshot grounding:
# [agent]
# grounding_strategy = "text_choice"
