## Base SeeAct configuration

[basic]
is_demo = false
save_file_dir = "../online_results"
default_task = "Find pdf of paper \"GPT-4V(ision) is a Generalist Web Agent, if Grounded\" from arXiv"
default_website = "https://www.google.com/"
crawler_mode = false
crawler_max_steps = 10

[experiment]
task_file_path = "../data/online_tasks/sample_tasks.json"
overwrite = false
top_k = 50
fixed_choice_batch_size = 22
dynamic_choice_batch_size = 0
max_continuous_no_op = 2
max_op = 20
highlight = false
monitor = false
dev_mode = false
include_dom_in_choices = false

[agent]
input_info = ["screenshot"]
grounding_strategy = "text_choice_som"
max_auto_op = 50
max_continuous_no_op = 5
highlight = false
heuristic = false

[openai]
rate_limit = -1
model = "gpt-4o-mini"
temperature = 0
timeout_sec = 20

[playwright]
save_video = false
tracing = false
locale = "en-US"
geolocation.longitude = 39.99542778404405
geolocation.latitude = -83.0068669912263
viewport.width = 1024
viewport.height = 600
trace.screenshots = true
trace.snapshots = true
trace.sources = true

[runtime]
provider   = "browserbase"
project_id = "${BROWSERBASE_PROJECT_ID}"

[runner]
concurrency = 10
max_retries = 0
backoff_base_sec = 1.5
backoff_max_sec = 15.0
task_timeout_sec = 180
metrics_dir = "../runs"
verbose = false

[manifest]
cache_dir = "../site_manifest"
refresh_days = 7

[macros]
product_href_patterns = ["/products", "/product"]
product_section_selectors = ["main", "section[role='main']"]
exclude_regions.bottom_fraction = 0.2
exclude_regions.top_fraction = 0.0
variant_labels = ["size", "color", "variant", "style"]
atc_selectors = ["button[name*='add']", "button:has-text('add to cart')", "form[action*='/cart/add'] button[type='submit']"]
checkout_selectors = ["button:has-text('checkout')", "a[href*='/checkout']"]
