## SeeAct config for running with an OpenAI fine‑tuned model

[basic]
is_demo = false
save_file_dir = "../online_results"
default_task = "Open the homepage and find a product"
default_website = "https://example.com/"

[experiment]
task_file_path = "../data/online_tasks/sample_tasks.json"
overwrite = false
top_k = 50
fixed_choice_batch_size = 17
dynamic_choice_batch_size = 1600
max_continuous_no_op = 2
max_op = 20
highlight = false
monitor = true
dev_mode = false

[openai]
rate_limit = -1
model = "ft:gpt-4o-mini:org:proj:YOUR_FINE_TUNE_ID"
temperature = 0

[oss_model]

[playwright]
save_video = false
tracing = false
locale = "en-US"
geolocation.longitude = 0
geolocation.latitude = 0
viewport.width = 1280
viewport.height = 720
trace.screenshots = true
trace.snapshots = true
trace.sources = true

[runtime]
provider = "local"

[runner]
concurrency = 6
max_retries = 2
backoff_base_sec = 1.5
backoff_max_sec = 15.0
task_timeout_sec = 180
metrics_dir = "../runs"

